### ISSUE TITLE
After upgrading to 2.0.12, service no longer exists

### ISSUE THREAD

**Issue by mind12** [hyperion-project/hyperion.ng#1412]
- [x] I confirm that this is an issue rather than a question.

## Bug report

After updating hyperion from alpha 11 to the latest 2.0.12 version the service no longer exists.
Alpha 11 was installed using the repository on Ubuntu 20.04.3 LTS based on the install guide:
https://docs.hyperion-project.org/en/user/Installation.html#rpi-debian-ubuntu

#### Steps to reproduce
Update using apt.

Reinstallation throws this error about the service:
/var/lib/dpkg/info/hyperion.postinst: 81: [: hyperion@ubuntu.service: unexpected operator
but while checking the script this is because the service does not exist anymore.

#### What is expected?
Service exists and starts automatically

#### What is actually happening?
Unit hyperion@ubuntu.service could not be found.

#### System

Hyperion can't start.

**Comment by mind12** [comment]
Reference: https://github.com/hyperion-project/hyperion.ng/issues/1350#issuecomment-975904017

**Comment by mind12** [comment]
Fixed it by creating the file manually:
(ubuntu is my username)

nano /etc/systemd/system/hyperion@.service
```
[Unit]
Description=Hyperion ambient light systemd service  for user %i
Documentation=https://docs.hyperion-project.org
Requisite=network.target
Wants=network-online.target
After=network-online.target
After=systemd-resolved.service

[Service]
ExecStart=/usr/bin/hyperiond
WorkingDirectory=/usr/share/hyperion/bin
User=%i
TimeoutStopSec=5
KillMode=mixed
Restart=on-failure
RestartSec=2

[Install]
WantedBy=multi-user.target
```
systemctl enable hyperion@ubuntu.service
systemctl start hyperion@ubuntu

**Comment by mind12** [comment]
You closed this but it's still an issue, during an upgrade the service is not recreated.
I have only provided a manual workaround.

**Comment by Paulchen-Panther** [comment]
Instead of throwing around false facts that it is still an issue, you should rather take a look at what steps are performed during an update. The bug has already been fixed.

**Comment by mind12** [comment]
> Instead of throwing around false facts that it is still an issue, you should rather take a look at what steps are performed during an update. The bug has already been fixed.
> 
> P.S.: To enlighten you a little. When updating, the Prerm script of the old version is executed before the new Postinst script of the new version is started. But since there was a typo in the prerm script in Alpha 11, the service was removed. References: https://www.debian.org/doc/debian-policy/ch-maintainerscripts.html [df14958#diff-a19b2a4e3f3691cf686bf04165c9b480885d25ee913744e5c45f0fd7934e540dL12](https://github.com/hyperion-project/hyperion.ng/commit/df149583d312085ddce8194cc40c280efd88ff4e#diff-a19b2a4e3f3691cf686bf04165c9b480885d25ee913744e5c45f0fd7934e540dL12)

The correct way to close issues is this way, with a reference why is it resolved/closed. We are not a developer to go through all the details to check what caused it and where was it resolved. Thx

**Comment by jeeftor** [comment]
I also found this issue:
https://github.com/hyperion-project/hyperion.ng/issues/1412
