### ISSUE TITLE
Screen caprture error

### ISSUE THREAD

**Issue by Jhon-Mosk** [hyperion-project/hyperion.ng#1824]
- [x] I confirm that this is an issue rather than a question.

#### Steps to reproduce

I select screen capture

![Image](https://github.com/user-attachments/assets/31ab2293-bf8c-4128-93b0-64dae4252515)

and hyperion reboots

![Image](https://github.com/user-attachments/assets/083085f3-5069-481a-9dd7-9053187f77e5)

#### What is expected?

That hyperion will find the graphics card and it will be possible to capture the output to the screen

#### What is actually happening?

Hyperion reboots

#### System

Hyperion Server:
- Build:             master (GitHub-4f03adf/61bfc2e-1735802751)
- Build time:        Jan 12 2025 09:19:09
- Git Remote:        https://github.com/hyperion-project/hyperion.ng.git
- Version:           2.0.17-beta.2
- UI Lang:           en (BrowserLang: ru)
- UI Access:         expert
- Avail Screen Cap.: framebuffer,x11,xcb,qt
- Avail Video  Cap.: v4l2
- Avail Audio  Cap.: audio
- Avail Services:    boblight,cec,effectengine,forwarder,flatbuffer,protobuffer,mDNS,SSDP,borderdetection
- Config database:   /root/.hyperion/db/hyperion.db
- Database:          read/write
- Mode:              Non-GUI

Hyperion Server OS:
- Distribution:      Fedora Linux 41 (Workstation Edition)
- Architecture:      x86_64
- CPU Model:         Intel(R) Core(TM) i7-7700K CPU @ 4.20GHz
- CPU Type:          158
- Kernel:            linux (6.12.8-200.fc41.x86_64 (WS: 64))
- Root/Admin:        true
- Qt Version:        6.8.1
- Python Version:    3.13.1
- Browser:           Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 YaBrowser/24.12.0.0 Safari/537.36

**Comment by Lord-Grey** [comment]
@Jhon-Mosk Thank you for reporting. A small bug sneaked in...
It is fixed by #1825 .

**Comment by Jhon-Mosk** [comment]
Thanks, on weekend I'll rebuild hyperion and try screen capture.

**Comment by Lord-Grey** [comment]
> Thanks, on weekend I'll rebuild hyperion and try screen capture.

You can also try a ready made PR build…

See [here](https://docs.hyperion-project.org/user/advanced/Testing.html#linux) how to test the PR easily.

**Comment by Jhon-Mosk** [comment]
> > Thanks, on weekend I'll rebuild hyperion and try screen capture.
> 
> You can also try a ready made PR build…
> 
> See [here](https://docs.hyperion-project.org/user/advanced/Testing.html#linux) how to test the PR easily.

I tested it, everything works. Three capture sources are defined. I tried X11 and QT, they work.

**Comment by Jhon-Mosk** [comment]
When should I wait for the release?

**Comment by Lord-Grey** [comment]
> I tested it, everything works. Three capture sources are defined. I tried X11 and QT, they work.

Thank you for testing and confirmation  it works.

**Comment by Lord-Grey** [comment]
> When should I wait for the release? Or should I clone and compile this pull request?

I just merged in PR into the master code branch

**Comment by Jhon-Mosk** [comment]
I built hyperion via docker, the error persists. I built it without docker, the error persists. I edited the script to build from a pull request and built it from a closed pull request, it works. Saved the configuration from the build from the pull request, applied it to the build from the source, does not work. I don't know what the problem might be.

**Comment by Jhon-Mosk** [comment]
@Lord-Grey Thank you very much, I installed the nightly build and it works correctly. I spent the whole day today compiling the source code and trying to figure out what settings are missing. Hyperion rebooted when trying to select a screen capture device.
