### ISSUE TITLE
Windows PR Build doesnt start webui and links to ucrtbased.dll

### ISSUE THREAD

**Issue by brutez** [hyperion-project/hyperion.ng#1865]
- [x] I confirm that this is an issue rather than a question.

## Bug report
I downloaded the PR Build for PR 1856. i had to install Windows SDK to optain ucrtbased.dll (debug version) to make it run.

Dialog starts but no webui is loaded.

#### Steps to reproduce
- Download https://github.com/hyperion-project/hyperion.ng/actions/runs/14540504850
- install Windows SDK
- run hyperion

#### What is expected?
PR Build works without ucrtbased.dll but with ucrtbase.dll instead.

Hyperion will start the webui und opens a browser tab for localhost.

#### What is actually happening?
First Error Message that ucrtbased.dll is missing is displayed. After that fix hyperion starts but doesnt load the webui under usual port and Adresse.

#### System
 cant do, no webui (windows 11)

**Comment by Lord-Grey** [comment]
Which Windows Version are you using running?

**Comment by Paulchen-Panther** [comment]
I am aware of this problem (debug build). A fix (RelWithDebInfo Build) for this problem is coming later this week with other customizations.

**Comment by brutez** [comment]
> Which Windows Version are you running?

Windows 11

**Comment by Paulchen-Panther** [comment]
@brutez I hope with this PR the PR artifacts work for you again?
https://github.com/hyperion-project/hyperion.ng/actions/runs/15074510051

**Comment by Lord-Grey** [comment]
@brutez Could you share your hyperion configuration, please?

**Comment by brutez** [comment]
@Lord-Grey 

[hyperion db.zip](https://github.com/user-attachments/files/20362357/hyperion.db.zip)

[Hyperion-2.0.16-Backup (Keller) 2025.04.30.json](https://github.com/user-attachments/files/20362349/Hyperion-2.0.16-Backup.Keller.2025.04.30.json)

**Comment by Lord-Grey** [comment]
@brutez Thank you for providing your configuration.
Unfortunately, UI was not able to reproduce a crash on my system (I had not the chance running WLED).

**Comment by brutez** [comment]
Thanks for testing my config. Its running good on 2.0.16 but will crash on 2.0.17 when streaming starts. So maybe the part with streaming to wled is needed.

**Comment by Lord-Grey** [comment]
Hi @brutez We did some updates to the Windows build.
Would you mind testing the latest version (https://github.com/hyperion-project/hyperion.ng/actions/runs/15475771940), please?

I installed on a fresh Windows 11 with your config and do not see any aborts...

**Comment by brutez** [comment]
@Lord-Grey 
> Hi [@brutez](https://github.com/brutez) We did some updates to the Windows build. Would you mind testing the latest version (https://github.com/hyperion-project/hyperion.ng/actions/runs/15475771940), please?
> 
> I installed on a fresh Windows 11 with your config and do not see any aborts...

Hi again, tested QT 5 and 6 Build. OT Grabber seems stable. DX Grabber is still broken. If i switch to DXGI DDA it crashs after a minute with the same old application error in Qt5Core.dll or Qt6Core.dll. Plus Lights are alot brighter with DX Grabber. Is that supposed to be like that?

QT 5 EventData 

  AppName hyperiond.exe 
  AppVersion 2.0.17.0 
  AppTimeStamp 6841f389 
  ModuleName Qt5Core.dll 
  ModuleVersion 5.15.2.0 
  ModuleTimeStamp 5fa4dd3b 
  ExceptionCode c00000fd 
  FaultingOffset 00000000002dc9a8 
  ProcessId 0x4988 
  ProcessCreationTime 0x1dbdb7af6694ff5 
  AppPath E:\Programme\Hyperion\Hyperion\bin\hyperiond.exe 
  ModulePath E:\Programme\Hyperion\Hyperion\bin\Qt5Core.dll 
  IntegratorReportId 699e7ebe-d1b9-4980-8f20-a643ebbfdf22 
  PackageFullName  
  PackageRelativeAppId  


QT 6 EventData 

  AppName hyperiond.exe 
  AppVersion 2.0.17.0 
  AppTimeStamp 6841f40d 
  ModuleName Qt6Core.dll 
  ModuleVersion 6.8.3.0 
  ModuleTimeStamp 67d82d3a 
  ExceptionCode c00000fd 
  FaultingOffset 0000000000393147 
  ProcessId 0x4e70 
  ProcessCreationTime 0x1dbdb79956a439a 
  AppPath E:\Programme\Hyperion\Hyperion\bin\hyperiond.exe 
  ModulePath E:\Programme\Hyperion\Hyperion\bin\Qt6Core.dll 
  IntegratorReportId 120d281d-ad4d-4fbb-939b-d5429922f550 
  PackageFullName  
  PackageRelativeAppId  

Beside that Dominant Color on all Leds is really nice, thanks for coding!

**Comment by Lord-Grey** [comment]
Thanks for comming back.
I am not sure which version you are testing.
In the run I shared, there is no DX support included any longer…
I would suggest you remove your current installation and install a fresh 2.1 which we just released.

**Comment by brutez** [comment]
@Lord-Grey still crashing. desktop is working fine but as soon as i launch any app it crashes after a few sec.
Its reproducible: start windows, start hyperion, open steam or the xbox app, hyperion crash. i also have to turn the components off and on at the dashboard every restart or else it blinks and flickers the whole time.

Reverted back to 2.0.16. no crashes but no new features also
Crashing happens only if dominant color is selected in new builds

btw: the PR Build bug is fixed
