### ISSUE TITLE
Gamma controls do not appear to work for blue and green

### ISSUE THREAD

**Issue by Iridahonda** [hyperion-project/hyperion.ng#493]
I guess this might already be fixed in the Beta Rework but thought I would mention it anyway.
When using the gamma controls from the web remote control only the red adjustment appears to be functional.

**Comment by MartB** [comment]
Can confirm and its not fixed in the beta rework as far as i can tell, i might take a look at this later.

**Comment by MartB** [comment]
Im confident that i fixed this it works on my builds now.

**Comment by Iridahonda** [comment]
I tried the new fix but I'm still getting something odd during startup.  Seems all gamma is set 1.0 until adjusted via remote control.

Think init is being called several times at startup and it leaves 1.0 in all RGB gamma

Maybe remove/edit this init as its called last during startup?

RgbTransform::RgbTransform()
{
        init(1.0, 1.0, 1.0, 0.0, false, 100, 100);   
}
